#!/bin/sh

SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")

cd "$SCRIPTPATH"

echo "rm -h"
../bin/rm.js -h
if [ "$?" != "0" ]; then exit 1; fi

echo "rm -V"
../bin/rm.js -V
if [ "$?" != "0" ]; then exit 1; fi

echo "rm"
../bin/rm.js
if [ "$?" != "1" ]; then exit 1; fi

echo "rm -Rz"
../bin/rm.js -Rz
if [ "$?" != "1" ]; then exit 1; fi

rm -rf out
mkdir out
touch out/a
mkdir out/b
mkdir out/c
touch out/c/d
mkdir out/d
touch out/d/e

echo "rm -D out/a"
../bin/rm.js -D out/a
if [ "$?" != "0" ]; then exit 1; fi
echo "checking out/a"
if [ ! -f "out/a" ]; then exit 1; fi

echo "rm -v out/a"
../bin/rm.js -v out/a
if [ "$?" != "0" ]; then exit 1; fi
echo "checking out/a"
if [ -f "out/a" ]; then exit 1; fi

echo "rm -- out/a"
../bin/rm.js -- out/a
if [ "$?" != "1" ]; then exit 1; fi

echo "rm out/b"
../bin/rm.js out/b
if [ "$?" != "1" ]; then exit 1; fi
echo "checking out/b"
if [ ! -d "out/b" ]; then exit 1; fi

echo "rm -d out/b"
../bin/rm.js -d out/b
if [ "$?" != "0" ]; then exit 1; fi
echo "checking out/b"
if [ -d "out/b" ]; then exit 1; fi

echo "rm -d out/c"
../bin/rm.js -d out/c
if [ "$?" != "1" ]; then exit 1; fi
echo "checking out/c"
if [ ! -d "out/c" ]; then exit 1; fi

echo "rm -rv out/c"
../bin/rm.js -r out/c
if [ "$?" != "0" ]; then exit 1; fi
echo "checking out/c"
if [ -d "out/c" ]; then exit 1; fi

echo "rm -f out/e"
../bin/rm.js -f out/e
if [ "$?" != "0" ]; then exit 1; fi

echo "rm --dir out/e"
../bin/rm.js --dir out/e
if [ "$?" != "1" ]; then exit 1; fi

echo "rm 'out/*/e'"
../bin/rm.js 'out/*/e'
if [ "$?" != "0" ]; then exit 1; fi
echo "checking out/d/e"
if [ -d "out/d/e" ]; then exit 1; fi

echo "rm -dv 'out/*'"
../bin/rm.js -dv 'out/*'
if [ "$?" != "0" ]; then exit 1; fi
echo "checking out/d"
if [ -d "out/d" ]; then exit 1; fi

echo "done"
