#!/bin/sh

SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")

cd "$SCRIPTPATH"

echo "rm -h"
../bin/rm.js -h
if [ "$?" != "0" ]; then exit 1; fi

echo "rm -V"
../bin/rm.js -V
if [ "$?" != "0" ]; then exit 1; fi

rm -rf out
mkdir out
touch out/a
mkdir out/b
mkdir out/c
touch out/c/d

echo "rm -D out/a"
../bin/rm.js -D out/a
if [ "$?" != "0" ]; then exit 1; fi
if [ ! -f "out/a" ]; then exit 1; fi

echo "rm out/a"
../bin/rm.js out/a
if [ "$?" != "0" ]; then exit 1; fi
if [ -f "out/a" ]; then exit 1; fi

echo "rm -- out/a"
../bin/rm.js -- out/a
if [ "$?" != "1" ]; then exit 1; fi

echo "rm out/b"
../bin/rm.js out/b
if [ "$?" != "1" ]; then exit 1; fi

echo "rm -d out/b"
../bin/rm.js -d out/b
if [ "$?" != "0" ]; then exit 1; fi
if [ -d "out/b" ]; then exit 1; fi

echo "rm -f out/b"
../bin/rm.js -f out/b
if [ "$?" != "0" ]; then exit 1; fi

echo "rm -rv out/c"
../bin/rm.js -r out/c
if [ "$?" != "0" ]; then exit 1; fi
if [ -d "out/c" ]; then exit 1; fi

echo "done"
